### ISSUE TITLE
distance calculation

### ISSUE THREAD

**Issue by sowmiyadharmalingam86** [LearnTechWithUs/Stereo-Vision#10]
Distance= -593.97*average**(3) + 1506.8*average**(2) - 1373.1*average + 522.06

how do you substitute the values in the above...What is the equation you are using to get the  distance value.

**Comment by crypto-g245** [comment]
If you will see this file [https://github.com/LearnTechWithUs/Stereo-Vision/blob/master/Stereo%20Vision%20-%20Explanation%20-%20German.pdf](url) page 26-27 you will get a clear idea about it. But it is in German. 

Basically, After you get the disparity map. You measure and record the distance of the object and record their respective disparity values experimentally for multiple placements of the object. 

with these observations/data po ints, you can create the regression graph (can be done in MS Excel)  from which you can get the linear equation  'Distance= -593.97average**(3) + 1506.8average**(2) - 1373.1*average + 522.06'.
It might be different according to your setup.  After getting this equation you can directly use it in your code to get the distance.

for clear understanding see the screenshot attached here.

![image](https://user-images.githubusercontent.com/51653105/101614465-46199680-3a0d-11eb-87ab-3c897c6eb8e6.png)
