### ISSUE TITLE
Processing speed is too slow

### ISSUE THREAD

**Issue by OmarElziat** [LearnTechWithUs/Stereo-Vision#2]
-Processing speed is too slow, I need to make it faster what I should do?
-What is the maximum distance range? I got only 5 meters, Is there any way to get the distance reach about 8 meters??
-Should I input the distance between the two lenses in the code??

**Comment by LearnTechWithUs** [comment]
- There isn't much that can be done for speeding up the process besides running the program on a more powerfull CPU. Another solution could be to take smaller dimensions for the video input(e.g. 300px300p), diplaying less feature maps on the screen?. Look for a solution were u could process using a GPU ? The program is still a prototype, so we didn't bother too much for a more faster processing on the Disparity Map.

- Our use case didn't demand a long range so we didn't try, but what might work (testing needed) in our opinion is increasing the distance between the two cameras(Will get better results for the disparity map if you want to work on long range) and then tweak the parameters in Main_Stereo_Vision_Prog.py, line 155/ stereo = cv2.StereoSGBM_create(minDisparity = min_disp,... till line 163. Try finding the best parameters by experimenting.

- You don't need to input the focal f from the cameras in the code nor the distance between the two cameras ;)

Hope the answer will be helpfull :) Let us know how it worked out for you in speeding up the processing time and if/how you managed to increase the range ;)

Have a good day !
