### ISSUE TITLE
This project can only be applied to the detection target as a plane？

### ISSUE THREAD

**Issue by ariafisherwater** [LearnTechWithUs/Stereo-Vision#3]
excuse me，
I want to know if This project can only be applied to the detection target as a plane
please tell me,
thanks,
PS: Apologize for my poor English

**Comment by UndecidedBoy** [comment]
Hello,
This project was not designed to be able to make detection in any way.
It only creates a disparity map of the scene in front of the stereo camera.
Hope it helps.
Have a nice day/evening!
