### ISSUE TITLE
Clarity on dependency versions

### ISSUE THREAD

**Issue by bw42** [LearnTechWithUs/Stereo-Vision#4]
It is unclear what the versions of dependencies (OpenCV, numpy etc) this successfully works with and have had some issues running out of the box. Can you be more specific on environment configuration and versions please. Thanks

**Comment by UndecidedBoy** [comment]
Hello,
Following version have been used for the project:
- Python v.2.7.13
- numpy v.1.12.1rc1
- opencv v.3.2.0
- openpyxl v.2.4.8
- sklearn v.0.18.1

Environment:
- WIndows 8, 64 bits

Hope this helps!

Check the youtube video, most of the questions (sometimes usefull) were asked in the comment section:
https://www.youtube.com/watch?v=xjx4mbZXaNc

Have a nice evening/day!
