### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by XAB745220zt** [LearnTechWithUs/Stereo-Vision#6]
How big is his error?

**Comment by XAB745220zt** [comment]
I want to know what length of the calibration plate grid you use?
I have not seen it in your program, can you tell me in detail?

**Comment by XAB745220zt** [comment]
@LearnTechWithUs

**Comment by UndecidedBoy** [comment]
First of all hello!

What error are you talking about? Be more precise.
The grid length does not matter, what matters is the number of grid corners you show for the calibration.
Ideally, you would like to use a chessboard as dense and as big as possible.

In the meantime have a nice day/evening ;)

P.S:
Next time if you have an issue or a question, don't call it "help me" and have you searched for similar question's in the comment section of our youtube video?
