### ISSUE TITLE
ximgproc

### ISSUE THREAD

**Issue by IvanD1993** [LearnTechWithUs/Stereo-Vision#9]
Hi,  
When I try to run the main program I got the following error:
AttributeError: module 'cv2' has no attribute 'ximgproc'

Does I need any additional libraries?

**Comment by Starlin-Dragonfly** [comment]
Yes, there are many possibilities for this problem. For example, this attribute has been patented and this version of CV2 library no longer supports it. It can be solved by downloading opencv-python 3.4.2.16 and opencv-contrib-python 3.4.2.16.
